//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Web.Security;

namespace ToDo
{
    using System;
    using System.Collections.Generic;
    
    public partial class item : MembershipUser
    {
        public int iditem { get; set; }
        public string description { get; set; }
        public Nullable<sbyte> done { get; set; }
    }
}
