//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDo
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public int iditem { get; set; }
        public string description { get; set; }
        public Nullable<sbyte> done { get; set; }
        public int id_userlogin { get; set; }
        public System.DateTime creationTime { get; set; }
    
        public virtual userlogin userlogin { get; set; }
    }
}
